### ISSUE TITLE
autocommit argument when creating Pool

### ISSUE THREAD

**Issue by gungorkdr** [prprprus/PyMySQLPool#4]
Can you add autocommit argument to Pool?
I know according to PEP 249 autocommit should be initially off but I like the way I can change it to True.

**Comment by prprprus** [comment]
Hi.

Your suggestion is great, I also thought about this before. But in my actual work, I don't see many scenarios that require auto-commit. If anyone else has this need, I will add this feature.😊

**Comment by krebbi** [comment]
tried it. doesn't seem to work.

https://github.com/sdispater/orator/issues/143#issuecomment-280695286

**Comment by krebbi** [comment]
I would need that argument too.

**Comment by prprprus** [comment]
MySQL supports autocommit so I think it's just a matter of [mysql-python](https://github.com/arnaudsj/mysql-python).

For [PyMySQL](https://github.com/PyMySQL/PyMySQL) it should be ok. https://github.com/PyMySQL/PyMySQL/blob/master/pymysql/connections.py#L158

Since there are still people who need it, I will add this it.

**Comment by prprprus** [comment]
Already added.😃

**Comment by gungorkdr** [comment]
Thanks for your support @krebbi 
And @prprprus , you're the king!

**Comment by prprprus** [comment]
Thanks for your advice. @gungorkdr @krebbi 👍❤️
